### ISSUE TITLE
tensorboardX version cause problems

### ISSUE THREAD

**Issue by LEE-JYOUNG** [ConvLab/ConvLab#104]
##  I have finished convlab‘env config following the instruction, a problem occurs:
>  Invalid proto descriptor for file "tensorboard/compat/proto/resource_handle.proto":
  tensorboard.ResourceHandleProto.device: "tensorboard.ResourceHandleProto.device" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.container: "tensorboard.ResourceHandleProto.container" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.name: "tensorboard.ResourceHandleProto.name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.hash_code: "tensorboard.ResourceHandleProto.hash_code" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.maybe_type_name: "tensorboard.ResourceHandleProto.maybe_type_name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto: "tensorboard.ResourceHandleProto" is already defined in file "tensorboardX/src/resource_handle.proto".
## then I uninstall tensorboardX=1.2.0 and installed a higher version 1.8.0. It works well.
but there is a  new problem occured:
>  ERROR: allennlp 0.8.2 has requirement pytz==2017.3, but you'll have pytz 2019.1 which is incompatible.
ERROR: allennlp 0.8.2 has requirement tensorboardX==1.2, but you'll have tensorboardx 1.8 which is incompatible.

## the allennlp also required in requirements.txt

**Comment by jincli** [comment]
@LEE-JYOUNG  Thanks for asking the question. The package was developed and tested with tensorflow==1.13.1 (tensorboardX=1.2), so please try the same version to ensure everything works as expected. If it still does not work, I would suggest using docker env, as described in the instruction, instead.

**Comment by LEE-JYOUNG** [comment]
> @LEE-JYOUNG Thanks for asking the question. The package was developed and tested with tensorflow==1.13.1 (tensorboardX=1.2), so please try the same version to ensure everything works as expected. If it still does not work, I would suggest using docker env, as described in the instruction, instead.


Should I config the conda env agin when using the docker env? when i run the convlab:convlab/convlab:0.2.2 , i found it's a more troublesome job.

**Comment by LEE-JYOUNG** [comment]
###  when runing convlab ,a new problem occurs:
>  python run.py {spec file} {spec name} {mode}
> Traceback (most recent call last):
  File "run.py", line 102, in <module>
    main()
  File "run.py", line 91, in main
    read_spec_and_run(*args)
  File "run.py", line 68, in read_spec_and_run
    run_spec(spec, lab_mode)
  File "run.py", line 49, in run_spec
    Session(spec).run()
  File "/home/lee/git_space/ConvLab/convlab/experiment/control.py", line 51, in __init__
    self.agent, self.env = make_agent_env(self.spec, global_nets)
  File "/home/lee/git_space/ConvLab/convlab/experiment/control.py", line 22, in make_agent_env
    env = make_env(spec)
  File "/home/lee/git_space/ConvLab/convlab/env/__init__.py", line 25, in make_env
    env = MultiWozEnv(spec, e)
  File "/home/lee/git_space/ConvLab/convlab/env/multiwoz.py", line 202, in __init__
    self.u_env = MultiWozEnvironment(self.env_spec, worker_id, self.action_dim)
  File "/home/lee/git_space/ConvLab/convlab/env/multiwoz.py", line 54, in __init__
    self.nlu = NluClass(**params)
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/multiwoz/onenet/nlu.py", line 41, in __init__
    self.tokenizer = SpacyWordSplitter(language="en_core_web_sm")
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/allennlp/data/tokenizers/word_splitter.py", line 148, in __init__
    self.spacy = get_spacy_model(language, pos_tags, parse, ner)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/allennlp/common/util.py", line 293, in get_spacy_model
    spacy_download(spacy_model_name)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/spacy/cli/download.py", line 31, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/spacy/cli/download.py", line 54, in get_json
    r = requests.get(url)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36121c3c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2020-02-24 11:12:53,464 PID:16563 INFO archival.py _cleanup_archive_dir] removing temporary unarchived model dir at /tmp/tmpwanyep0j

### It seems a network error?

**Comment by jincli** [comment]
@LEE-JYOUNG  It seems like a network issue.  Does 'python -m spacy download en_core_web_sm' work in your env?

**Comment by LEE-JYOUNG** [comment]
@jincli Thanks for your apply，Run 'python -m spacy download en_core_web_sm'  error log as follows：
 > Traceback (most recent call last):
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5176d139e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5176d139e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lee/.conda/envs/convlab/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/spacy/cli/download.py", line 31, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/spacy/cli/download.py", line 54, in get_json
    r = requests.get(url)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5176d139e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

### should I have a vpn or there has other Domestic sources can be used?

**Comment by jincli** [comment]
@LEE-JYOUNG  Please check https://github.com/explosion/spacy-models 
I also suggest checking your network settings to avoid other potential issues.

**Comment by LEE-JYOUNG** [comment]
### Runing python run.py convlab/spec/demo.json onenet_rule_rule_template eval
>   File "run.py", line 21, in <module>
    from convlab.experiment.control import Session, Trial, Experiment
  File "/home/lee/git_space/ConvLab/convlab/experiment/control.py", line 11, in <module>
    from convlab import agent as agent_module
  File "/home/lee/git_space/ConvLab/convlab/agent/__init__.py", line 17, in <module>
    from convlab.modules import nlu, dst, word_dst, nlg, state_encoder, action_decoder
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/__init__.py", line 4, in <module>
    from convlab.modules.nlu.multiwoz import MILU
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/multiwoz/__init__.py", line 8, in <module>
    from convlab.modules.nlu.multiwoz.bert import BERTNLU
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/multiwoz/bert/__init__.py", line 3, in <module>
    from convlab.modules.nlu.multiwoz.bert.multiwoz.nlu import BERTNLU
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/multiwoz/bert/multiwoz/nlu.py", line 21, in <module>
    from convlab.modules.nlu.multiwoz.bert.dataloader import Dataloader
  File "/home/lee/git_space/ConvLab/convlab/modules/nlu/multiwoz/bert/dataloader.py", line 4, in <module>
    from transformers import BertTokenizer
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/transformers/__init__.py", line 20, in <module>
    from .file_utils import (TRANSFORMERS_CACHE, PYTORCH_TRANSFORMERS_CACHE, PYTORCH_PRETRAINED_BERT_CACHE,
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/transformers/file_utils.py", line 30, in <module>
    import tensorflow as tf
  File "/home/lee/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 35, in <module>
    from tensorflow._api.v1 import compat
  File "/home/lee/.local/lib/python3.6/site-packages/tensorflow/_api/v1/compat/__init__.py", line 22, in <module>
    from tensorflow._api.v1.compat import v2
  File "/home/lee/.local/lib/python3.6/site-packages/tensorflow/_api/v1/compat/v2/__init__.py", line 303, in <module>
    from tensorboard.summary._tf import summary
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 36, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n.tensorboard/compat/proto/resource_handle.proto\x12\x0btensorboard\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
  File "/home/lee/.conda/envs/convlab/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/resource_handle.proto":
  tensorboard.ResourceHandleProto.device: "tensorboard.ResourceHandleProto.device" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.container: "tensorboard.ResourceHandleProto.container" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.name: "tensorboard.ResourceHandleProto.name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.hash_code: "tensorboard.ResourceHandleProto.hash_code" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.maybe_type_name: "tensorboard.ResourceHandleProto.maybe_type_name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto: "tensorboard.ResourceHandleProto" is already defined in file "tensorboardX/src/resource_handle.proto".
### how to slove this ?

**Comment by jincli** [comment]
@LEE-JYOUNG  It seems this is due to the dependency issues. I would suggest trying to uninstall and reinstall Tensorflow. Does 'from transformers import BertTokenizer' work for you? If not, probably also try to reinstall tranformers package.

**Comment by LEE-JYOUNG** [comment]
@jincli Follow your suggestion，I have found a tensorflow-gpu=1.14.0 in my conda env，which is not listed in requirements.txt ，I uninstalled it，it works，Thanks ！but, How can I run tensorflow on gpu?

**Comment by jincli** [comment]
@LEE-JYOUNG  TensorFlow-GPU should work if everything is installed correctly.  From the error message you showed, it seems that there is a problem with 'import tensorflow as tf'  when using the 'transformers' package.  You need to make sure these two are compatible.  Another thing about ConvLab is, we only have one model 'mdbt' implemented in TensorFlow. If you only use existing models except 'mdbt', you do not need to take care of TensorFlow on GPU.

**Comment by LEE-JYOUNG** [comment]
@jincli Thanks
