### ISSUE TITLE
Sc-lstm training is not working

### ISSUE THREAD

**Issue by mrcmoresi** [ConvLab/ConvLab#105]
Dear,
I tried to train the sc-lstm module and it didn't work, please find the log below.
What could be the error?

```
mrc@marco-instance-0:~/ConvLab/convlab/modules/nlg/multiwoz/sc_lstm$ PYTHONPATH=../../../../.. python3 run_woz.py  --mode=train --model_path=sclstm.pt --n_layer=1 --lr=0.005 > sclstm.log
Processing data...
# of turns
Train: 26414
Valid: 3171
Test: 3154
# of batches: Train 103 Valid 12 Test 12
Using deep version with 1 layer
Start training
Epoch 0 (n_layer 1)
Traceback (most recent call last):
  File "run_woz.py", line 382, in <module>
    train(config, args)
  File "run_woz.py", line 226, in train
    train_epoch(config, dataset, model)
  File "run_woz.py", line 144, in train_epoch
    _ = model(input_var, dataset, feats_var)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrc/ConvLab/convlab/modules/nlg/multiwoz/sc_lstm/model/lm_deep.py", line 50, in forward
    gen=gen, sample_size=sample_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrc/ConvLab/convlab/modules/nlg/multiwoz/sc_lstm/model/layers/decoder_deep.py", line 155, in forward
    output, last_hidden, last_cell, last_dt = self.rnn_step(vocab_t, last_hidden, last_cell, last_dt, gen=gen)
  File "/home/mrc/ConvLab/convlab/modules/nlg/multiwoz/sc_lstm/model/layers/decoder_deep.py", line 111, in rnn_step
    _hidden, _cell, _dt = self._step(input_t, last_hidden, last_cell[i], last_dt[i], i)
  File "/home/mrc/ConvLab/convlab/modules/nlg/multiwoz/sc_lstm/model/layers/decoder_deep.py", line 69, in _step
    w2h = self.w2h[layer_idx](input_t) # (batch_size, hidden_size*4)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm
```

**Comment by truthless11** [comment]
@mrcmoresi We only support SC-LSTM training with CPU for now. You can refer to the [source code](https://github.com/andy194673/nlg-sclstm-multiwoz) for training with GPU. We will support it in the coming [Convlab-2](https://arxiv.org/abs/2002.04793). Sorry for the inconvenience.
