### ISSUE TITLE
Evaluation configuration and Pretrained MDBT 

### ISSUE THREAD

**Issue by hwaranlee** [ConvLab/ConvLab#48]
1) Evaluation
For automatic end2end evaluation, it is denoted that ``The submitted system will be evaluated using the current user-simulator in the repository with milu-rule-template configuration. `` Can you describe the exact configuration in Conv/convlab/spec folder? 

2) mdbt_rule_template configure
For mdbt_rule_tremplate configure, can we download the pretrained mdbt model? It is because currently we can't train any components except policy models.

``python run.py demo.json mdbt_rule_template eval``
> FileNotFoundError: [Errno 2] No such file or directory: 'data/mdbt/word-vectors/paragram_300_sl999.txt'

3) onenet_rule_mdrg
For this configuration, I faced with the following errors. 
> Response generation error
> IndexError: list index out of range

Do you have any idea for this?

Thank you

**Comment by pengbaolin** [comment]
Hi @hwaranlee 
Q1: We will use "milu_rule_rule_template" in demo.json.
Q2: We adapted the mdbt code from https://github.com/osmanio2/multi-domain-belief-tracking. You may use the repo to train your own tracker. A pretraiend tracker model and word vectors are needed in order to run mdbt. The vector can be downloaded from https://convlab.blob.core.windows.net/models/paragram_300_sl999.zip. We probably could provide pretrained model, will let you know later.
Q3: The error rises from mdrg. Thanks for pointing out. We will look into it.

**Comment by hwaranlee** [comment]
Thank you!

BTW, the configuration 'squicity' also raises errors:
```
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hwaranlee/06_convlab/convlab/experiment/control.py", line 32, in mp_run_session
    metrics = session.run()
  File "/home/hwaranlee/06_convlab/convlab/experiment/control.py", line 146, in run
    metrics = analysis.analyze_session(self.spec, self.agent.body.eval_df, 'eval')
  File "/home/hwaranlee/06_convlab/convlab/experiment/analysis.py", line 173, in analyze_session
    assert len(session_df) > 1, f'Need more than 1 datapoint to calculate metrics'
AssertionError: Need more than 1 datapoint to calculate metrics
[2019-08-16 05:03:18,843 PID:4471 INFO archival.py _cleanup_archive_dir] removing temporary unarchived model dir at /tmp/tmpef5gz1w8
[2019-08-16 05:03:18,847 PID:4471 INFO archival.py _cleanup_archive_dir] removing temporary unarchived model dir at /tmp/tmpqwgv0zk5
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    main()
  File "run.py", line 91, in main
    read_spec_and_run(*args)
  File "run.py", line 68, in read_spec_and_run
    run_spec(spec, lab_mode)
  File "run.py", line 45, in run_spec
    Trial(spec).run()
  File "/home/hwaranlee/06_convlab/convlab/experiment/control.py", line 204, in run
    metrics = analysis.analyze_trial(self.spec, session_metrics_list)
  File "/home/hwaranlee/06_convlab/convlab/experiment/analysis.py", line 186, in analyze_trial
    trial_metrics = calc_trial_metrics(session_metrics_list, info_prepath)
  File "/home/hwaranlee/06_convlab/convlab/experiment/analysis.py", line 133, in calc_trial_metrics
    frames = session_metrics_list[0]['local']['frames']
IndexError: list index out of range
```

**Comment by jincli** [comment]
@hwaranlee  We just tried sequicity config with 'python run.py demo.json sequicity eval', and it works for us. Will you try it again? Which command and config did you use?

**Comment by hwaranlee** [comment]
@jincli Oh, It was my mistake, I tried train mode rather than eval. Now it works. Thanks!
