### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by twoflypig** [ConvLab/ConvLab#68]
Hi, I clone the code and find  the following error when executing
> python run.py demo.json onenet_rule_rule_template eval

I run it in python3.6.5, so anyone can help?
```
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    main()
  File "run.py", line 91, in main
    read_spec_and_run(*args)
  File "run.py", line 68, in read_spec_and_run
    run_spec(spec, lab_mode)
  File "run.py", line 49, in run_spec
    Session(spec).run()
  File "/home/super/DSTC8/ConvLab/convlab/experiment/control.py", line 142, in run
    self.run_eval()
  File "/home/super/DSTC8/ConvLab/convlab/experiment/control.py", line 95, in run_eval
    avg_return, avg_len, avg_success, avg_p, avg_r, avg_f1, avg_book_rate = analysis.gen_avg_result(self.agent, self.eval_env, self.num_eval) 
  File "/home/super/DSTC8/ConvLab/convlab/experiment/analysis.py", line 68, in gen_avg_result
    returns.append(gen_result(agent, env))
  File "/home/super/DSTC8/ConvLab/convlab/experiment/analysis.py", line 59, in gen_result
    _return = gen_return(agent, env)
  File "/home/super/DSTC8/ConvLab/convlab/experiment/analysis.py", line 35, in gen_return
    next_obs, reward, done, info = env.step(action)
  File "/home/super/DSTC8/ConvLab/convlab/env/multiwoz.py", line 242, in step
    env_info_dict = self.u_env.step(action)
  File "/home/super/DSTC8/ConvLab/convlab/env/multiwoz.py", line 110, in step
    action = da_normalize(action, role='sys')
  File "/home/super/DSTC8/ConvLab/convlab/modules/util/multiwoz/da_normalize.py", line 71, in da_normalize
    for act, svs in das.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by zqwerty** [comment]
Fixed, thanks!
