### ISSUE TITLE
MultiWoz action decoder KeyError: 'Ref'

### ISSUE THREAD

**Issue by ChansongJo** [ConvLab/ConvLab#70]
>> python run.py milu_rule_dqn_template train

[2019-09-10 22:23:58,059 PID:6203 INFO __init__.py log_summary] Trial 0 session 0 milu_rule_dqn_template_t0_s0 [train_df] epi: 124  t: 20  wall_t: 520  opt_step: 120000  frame: 2499  fps: 4.80577  total_reward: -59  avg_return: -58.78  avg_len: nan  avg_success: nan  loss: 0.0269472  lr: 0.001  explore_var: 0.0997296  entropy_coef: nan  entropy: nan  grad_norm: nan
Process Process-2:
Traceback (most recent call last):
  File "/home/ddpghgg/anaconda3/envs/convlab/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ddpghgg/anaconda3/envs/convlab/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ddpghgg/ConvLab/convlab/experiment/control.py", line 32, in mp_run_session
    metrics = session.run()
  File "/home/ddpghgg/ConvLab/convlab/experiment/control.py", line 145, in run
    self.run_rl()
  File "/home/ddpghgg/ConvLab/convlab/experiment/control.py", line 128, in run_rl
    action = self.agent.act(obs)
  File "/home/ddpghgg/ConvLab/convlab/agent/__init__.py", line 149, in act
    output_act, decoded_action = self.action_decode(action, self.body.state)
  File "/home/ddpghgg/ConvLab/convlab/agent/__init__.py", line 187, in action_decode
    output_act = self.action_decoder.decode(action, state) if self.action_decoder else action
  File "/home/ddpghgg/ConvLab/convlab/modules/action_decoder/multiwoz/multiwoz_vocab_action_decoder.py", line 97, in decode
    action[act] = [["Ref", kb_result[0]["Ref"]]]
KeyError: 'Ref'

Hi I was just following the demo code, but got an Key Error in multiwoz_vocab_action_decoder.py where it retrieves the results from db query. It seems that the result db_query don't have a key of "Ref" in it.

**Comment by truthless11** [comment]
Fixed. #71
